### PR TITLE
Moving to PHP 8 + Adding a CI workflow

### PR DESCRIPTION
**Pull request by lbouriez**
Change base image to alpine
Update PHP 7 to PHP8
Adding a CI workflow to control the Build
Issue: #6

### CODE REVIEW

**Comment by lunik1** [comment]
Thanks for the contribution.

I think this patch adds too much. The introduction of CI should at least be a separate patch.

I am not convinced the added maintenance burden of having to manage our own nginx and php config is worth the upgrade to php8, if that is what it takes. I would rather hem more closely to lsio. It may be better to revisit php8 if the lsio nginx container starts to support it or tt-rss starts to require it.

I intended #6 as more of a "nice to have deadline someday" item, but I might be unaware of a more pressing reason to make the change.

**Comment by lbouriez** [comment]
I understand, I will close it.
On my side I am using it since a week and it works pretty well till now.

**Comment by lunik1** [comment]
Still might be worth pushing to docker hub for others who might want php8, so long as you don't mind maintaining it!

**Comment by lbouriez** [comment]
I won't maintain it, I only forked it to contribute to your repo :)
I only maintain my [HomeAssistant addon](https://github.com/lbouriez/addon-tt-rss).

**Pull request closed without merging**
